name = "MoziFENode"
uuid = "bc5e1aea-ccfc-42b4-a639-d0a9cb9ca5ed"
authors = ["HZJ <zhuoju36@hotmail.com>"]
version = "0.1.0"

[deps]
MoziCSys = "6caa8793-38a2-477f-bdca-0f7426d014a4"
MoziFESparse = "38b32a81-66d9-4e97-ab3b-d94dedfcc576"

[compat]
MoziCSys = "^0.1.0"
MoziFESparse = "^0.1.0"